name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *' # Runs at 12:30am IST (adjust as needed)

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"    
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "Updated README with Dev Metrics"
          LOCALE: "id"            
