name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *' # Runs at 12:30am IST (adjust as needed)

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: "True"        # Menampilkan bahasa pemrograman
          SHOW_OS: "True"             # Menampilkan sistem operasi
          SHOW_PROJECTS: "True"       # Menampilkan proyek yang dikerjakan
          SHOW_TIMEZONE: "True"       # Menampilkan zona waktu
          SHOW_EDITORS: "True"        # Menampilkan editor yang digunakan
          SHOW_LANGUAGE_PER_REPO: "True"  # Menampilkan bahasa di setiap repositori
          SHOW_SHORT_INFO: "True"     # Menampilkan informasi singkat tentang pengguna
          COMMIT_BY_ME: "True" 
          COMMIT_MESSAGE: "Updated README with Dev Metrics"
          LOCALE: "en"            
